// Code generated by cmd/egress-gen from egress.yaml. DO NOT EDIT.

package cli

// egressGeneratedText 是 `tokenhush privacy` 打印的人类可读披露。
const egressGeneratedText = "" +
	"Tokenhush network egress disclosure\n" +
	"===================================\n" +
	"Generated from egress.yaml (version 1, updated 2026-09-13). Do not edit by hand.\n" +
	"\n" +
	"Vendor-bound requests are limited to the two switchable categories below.\n" +
	"Each can be switched off. Categories marked [PLANNED] are not active in this build.\n" +
	"\n" +
	"[PLANNED] Update check (update-check)\n" +
	"  Host: updates.tokenhush.com\n" +
	"  Purpose: Check for a signed release: the update manifest, its signed revocation document, and the root-signed key-list. These share one host and one switch and are one egress category, not three.\n" +
	"  Sent to the server:\n" +
	"    - channel: Release channel requested (for example stable or beta).\n" +
	"    - os_arch: Operating system and CPU architecture of the running binary.\n" +
	"    - current_version: Current binary version, so the server can tell whether an update exists.\n" +
	"  Server can observe:\n" +
	"    - ip: Source IP address of the request, visible to the server.\n" +
	"    - timestamp: Request time recorded by the server.\n" +
	"    - access_logs: Cloudflare access logs (path, time, source IP, User-Agent).\n" +
	"  How to switch off: When this category is active, set `auto_update: false` in tokenhush.yaml, or set the environment variable `TOKENHUSH_NO_UPDATE_CHECK=1`.\n" +
	"  Default (when active): enabled\n" +
	"  Retention: Cloudflare access logs and request records are retained for 30 days.\n" +
	"\n" +
	"[ACTIVE] Rule sync (rule-sync)\n" +
	"  Host: updates.tokenhush.com\n" +
	"  Purpose: Fetch signed detection-rule manifests and rule bundles so the local detectors can be tightened without shipping a new binary.\n" +
	"  Sent to the server:\n" +
	"    - channel: Rule channel requested (for example stable or beta).\n" +
	"    - os_arch: Operating system and CPU architecture of the running binary.\n" +
	"    - current_schema_version: Schema version and serial of the rule set currently in use.\n" +
	"  Server can observe:\n" +
	"    - ip: Source IP address of the request, visible to the server.\n" +
	"    - timestamp: Request time recorded by the server.\n" +
	"    - access_logs: Cloudflare access logs (path, time, source IP, User-Agent).\n" +
	"  How to switch off: Rule sync runs only when you run `tokenhush rules sync`; it never syncs on its own. Set the environment variable `TOKENHUSH_NO_RULE_SYNC=1` to make the command refuse without any network request.\n" +
	"  Default (when active): enabled\n" +
	"  Retention: Cloudflare access logs and request records are retained for 30 days.\n"

// egressGeneratedJSON 是 `tokenhush privacy --json` 打印的机器可读披露。
const egressGeneratedJSON = "" +
	"{\n" +
	"  \"version\": 1,\n" +
	"  \"updated\": \"2026-09-13\",\n" +
	"  \"items\": [\n" +
	"    {\n" +
	"      \"id\": \"update-check\",\n" +
	"      \"status\": \"planned\",\n" +
	"      \"host\": \"updates.tokenhush.com\",\n" +
	"      \"title\": {\n" +
	"        \"en\": \"Update check\",\n" +
	"        \"zh\": \"更新检查\"\n" +
	"      },\n" +
	"      \"purpose\": {\n" +
	"        \"en\": \"Check for a signed release: the update manifest, its signed revocation document, and the root-signed key-list. These share one host and one switch and are one egress category, not three.\",\n" +
	"        \"zh\": \"检查已签名的版本更新：更新清单、其签名撤销文档，以及根签名 key-list。 三者共用同一 host 与同一开关，属同一外发类别，而非三项。\"\n" +
	"      },\n" +
	"      \"fields\": [\n" +
	"        {\n" +
	"          \"name\": \"channel\",\n" +
	"          \"kind\": \"sent\",\n" +
	"          \"description\": {\n" +
	"            \"en\": \"Release channel requested (for example stable or beta).\",\n" +
	"            \"zh\": \"请求的发布通道（例如 stable 或 beta）。\"\n" +
	"          }\n" +
	"        },\n" +
	"        {\n" +
	"          \"name\": \"os_arch\",\n" +
	"          \"kind\": \"sent\",\n" +
	"          \"description\": {\n" +
	"            \"en\": \"Operating system and CPU architecture of the running binary.\",\n" +
	"            \"zh\": \"运行中二进制的操作系统与 CPU 架构。\"\n" +
	"          }\n" +
	"        },\n" +
	"        {\n" +
	"          \"name\": \"current_version\",\n" +
	"          \"kind\": \"sent\",\n" +
	"          \"description\": {\n" +
	"            \"en\": \"Current binary version, so the server can tell whether an update exists.\",\n" +
	"            \"zh\": \"当前二进制版本号，供服务端判断是否存在可用更新。\"\n" +
	"          }\n" +
	"        },\n" +
	"        {\n" +
	"          \"name\": \"ip\",\n" +
	"          \"kind\": \"observed\",\n" +
	"          \"description\": {\n" +
	"            \"en\": \"Source IP address of the request, visible to the server.\",\n" +
	"            \"zh\": \"请求的来源 IP 地址，服务端可见。\"\n" +
	"          }\n" +
	"        },\n" +
	"        {\n" +
	"          \"name\": \"timestamp\",\n" +
	"          \"kind\": \"observed\",\n" +
	"          \"description\": {\n" +
	"            \"en\": \"Request time recorded by the server.\",\n" +
	"            \"zh\": \"服务端记录的请求时间戳。\"\n" +
	"          }\n" +
	"        },\n" +
	"        {\n" +
	"          \"name\": \"access_logs\",\n" +
	"          \"kind\": \"observed\",\n" +
	"          \"description\": {\n" +
	"            \"en\": \"Cloudflare access logs (path, time, source IP, User-Agent).\",\n" +
	"            \"zh\": \"Cloudflare 访问日志（路径、时间、来源 IP、User-Agent）。\"\n" +
	"          }\n" +
	"        }\n" +
	"      ],\n" +
	"      \"switch\": {\n" +
	"        \"en\": \"When this category is active, set `auto_update: false` in tokenhush.yaml, or set the environment variable `TOKENHUSH_NO_UPDATE_CHECK=1`.\",\n" +
	"        \"zh\": \"该类别生效后，可在 tokenhush.yaml 设 `auto_update: false`， 或设置环境变量 `TOKENHUSH_NO_UPDATE_CHECK=1` 关闭。\"\n" +
	"      },\n" +
	"      \"default\": \"enabled\",\n" +
	"      \"retention\": {\n" +
	"        \"en\": \"Cloudflare access logs and request records are retained for 30 days.\",\n" +
	"        \"zh\": \"Cloudflare 访问日志与请求记录保留 30 天。\"\n" +
	"      }\n" +
	"    },\n" +
	"    {\n" +
	"      \"id\": \"rule-sync\",\n" +
	"      \"status\": \"active\",\n" +
	"      \"host\": \"updates.tokenhush.com\",\n" +
	"      \"title\": {\n" +
	"        \"en\": \"Rule sync\",\n" +
	"        \"zh\": \"规则同步\"\n" +
	"      },\n" +
	"      \"purpose\": {\n" +
	"        \"en\": \"Fetch signed detection-rule manifests and rule bundles so the local detectors can be tightened without shipping a new binary.\",\n" +
	"        \"zh\": \"获取已签名的检测规则清单与规则包，使本地检测器可增量收紧， 无需重新分发二进制。\"\n" +
	"      },\n" +
	"      \"fields\": [\n" +
	"        {\n" +
	"          \"name\": \"channel\",\n" +
	"          \"kind\": \"sent\",\n" +
	"          \"description\": {\n" +
	"            \"en\": \"Rule channel requested (for example stable or beta).\",\n" +
	"            \"zh\": \"请求的规则通道（例如 stable 或 beta）。\"\n" +
	"          }\n" +
	"        },\n" +
	"        {\n" +
	"          \"name\": \"os_arch\",\n" +
	"          \"kind\": \"sent\",\n" +
	"          \"description\": {\n" +
	"            \"en\": \"Operating system and CPU architecture of the running binary.\",\n" +
	"            \"zh\": \"运行中二进制的操作系统与 CPU 架构。\"\n" +
	"          }\n" +
	"        },\n" +
	"        {\n" +
	"          \"name\": \"current_schema_version\",\n" +
	"          \"kind\": \"sent\",\n" +
	"          \"description\": {\n" +
	"            \"en\": \"Schema version and serial of the rule set currently in use.\",\n" +
	"            \"zh\": \"当前所用规则包的 schema 版本与 serial。\"\n" +
	"          }\n" +
	"        },\n" +
	"        {\n" +
	"          \"name\": \"ip\",\n" +
	"          \"kind\": \"observed\",\n" +
	"          \"description\": {\n" +
	"            \"en\": \"Source IP address of the request, visible to the server.\",\n" +
	"            \"zh\": \"请求的来源 IP 地址，服务端可见。\"\n" +
	"          }\n" +
	"        },\n" +
	"        {\n" +
	"          \"name\": \"timestamp\",\n" +
	"          \"kind\": \"observed\",\n" +
	"          \"description\": {\n" +
	"            \"en\": \"Request time recorded by the server.\",\n" +
	"            \"zh\": \"服务端记录的请求时间戳。\"\n" +
	"          }\n" +
	"        },\n" +
	"        {\n" +
	"          \"name\": \"access_logs\",\n" +
	"          \"kind\": \"observed\",\n" +
	"          \"description\": {\n" +
	"            \"en\": \"Cloudflare access logs (path, time, source IP, User-Agent).\",\n" +
	"            \"zh\": \"Cloudflare 访问日志（路径、时间、来源 IP、User-Agent）。\"\n" +
	"          }\n" +
	"        }\n" +
	"      ],\n" +
	"      \"switch\": {\n" +
	"        \"en\": \"Rule sync runs only when you run `tokenhush rules sync`; it never syncs on its own. Set the environment variable `TOKENHUSH_NO_RULE_SYNC=1` to make the command refuse without any network request.\",\n" +
	"        \"zh\": \"规则同步只在你运行 `tokenhush rules sync` 时发生，绝不自动同步。 设置环境变量 `TOKENHUSH_NO_RULE_SYNC=1` 可使该命令拒绝同步且不发起任何网络请求。\"\n" +
	"      },\n" +
	"      \"default\": \"enabled\",\n" +
	"      \"retention\": {\n" +
	"        \"en\": \"Cloudflare access logs and request records are retained for 30 days.\",\n" +
	"        \"zh\": \"Cloudflare 访问日志与请求记录保留 30 天。\"\n" +
	"      }\n" +
	"    }\n" +
	"  ]\n" +
	"}\n"
