//go:build ignore

// egress_gen.go renders egress.yaml — the repository root's single source of
// truth for the vendor-bound egress disclosure (invariant 6) — into
// egress_generated.go, which is committed and compiled. It is the ONE folded
// codegen step: no second binary, no second package (Must-NOT-Have #13). The
// directive in privacy.go runs it with `go generate ./internal/cli`.
//
// The two-category rule is enforced here, so a third vendor-bound category
// cannot even be generated: the disclosure decision is the code change, never
// a YAML edit.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"runtime"

	"github.com/goccy/go-yaml"
)

// generatedHeader is the frozen first line of the generated file, in the
// canonical Go form so the size guard and gofmt both recognize it.
const generatedHeader = "// Code generated by egress_gen.go from egress.yaml. DO NOT EDIT.\n"

// disclosureDoc mirrors egress.yaml.
type disclosureDoc struct {
	Version    int        `yaml:"version"`
	Categories []category `yaml:"categories"`
}

// category is one vendor-bound egress category.
type category struct {
	Name      string `yaml:"name"`
	Switch    string `yaml:"switch"`
	Host      string `yaml:"host"`
	Retention string `yaml:"retention"`
}

func main() {
	root := moduleRoot()
	in := flag.String("in", filepath.Join(root, "egress.yaml"), "path of the disclosure source")
	out := flag.String("out", filepath.Join(root, "internal", "cli", "egress_generated.go"), "path of the generated file")
	toStdout := flag.Bool("stdout", false, "write the generated source to stdout instead of -out")
	flag.Parse()

	rendered, err := renderFile(*in)
	if err != nil {
		fatal(err)
	}
	if *toStdout {
		if _, err := os.Stdout.Write(rendered); err != nil {
			fatal(err)
		}
		return
	}
	if err := os.WriteFile(*out, rendered, 0o644); err != nil {
		fatal(fmt.Errorf("write %s: %w", *out, err))
	}
}

// moduleRoot is the repository root, derived from this file's location
// (<root>/internal/cli/egress_gen.go), so the generator works from any working
// directory.
func moduleRoot() string {
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		fatal(fmt.Errorf("resolve the module root"))
	}
	return filepath.Dir(filepath.Dir(filepath.Dir(file)))
}

// renderFile reads and renders one disclosure source.
func renderFile(in string) ([]byte, error) {
	raw, err := os.ReadFile(in)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", in, err)
	}
	var doc disclosureDoc
	if err := yaml.Unmarshal(raw, &doc); err != nil {
		return nil, fmt.Errorf("decode %s: %w", in, err)
	}
	return render(doc)
}

// render validates the disclosure and renders the generated Go source. Every
// field is required, both switches must be distinct, and exactly two
// categories may exist: a wider egress surface refuses to generate.
func render(doc disclosureDoc) ([]byte, error) {
	if doc.Version != 1 {
		return nil, fmt.Errorf("unsupported disclosure version %d, want 1", doc.Version)
	}
	if len(doc.Categories) != 2 {
		return nil, fmt.Errorf("the disclosure must declare exactly two categories, found %d", len(doc.Categories))
	}
	seen := map[string]bool{}
	for _, item := range doc.Categories {
		if item.Name == "" || item.Switch == "" || item.Host == "" || item.Retention == "" {
			return nil, fmt.Errorf("category %q must name its name, switch, host and retention", item.Name)
		}
		if seen[item.Switch] {
			return nil, fmt.Errorf("duplicate switch %s", item.Switch)
		}
		seen[item.Switch] = true
	}

	var body bytes.Buffer
	body.WriteString(generatedHeader)
	body.WriteString("\npackage cli\n\n")
	body.WriteString("// egressDisclosure is the vendor-bound egress disclosure of invariant 6,\n")
	body.WriteString("// rendered from egress.yaml. Exactly two categories; each names its switch,\n")
	body.WriteString("// the vendor host it would reach and its retention. egressCategory is declared\n")
	body.WriteString("// in privacy.go, which prints this disclosure.\n")
	body.WriteString("var egressDisclosure = []egressCategory{\n")
	for _, item := range doc.Categories {
		fmt.Fprintf(&body, "\t{Name: %q, Switch: %q, Host: %q, Retention: %q},\n",
			item.Name, item.Switch, item.Host, item.Retention)
	}
	body.WriteString("}\n")

	formatted, err := format.Source(body.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format the generated source: %w", err)
	}
	return formatted, nil
}

// fatal reports one generator failure and exits non-zero.
func fatal(err error) {
	fmt.Fprintln(os.Stderr, "egress_gen:", err)
	os.Exit(1)
}
