// Code generated by egress_gen.go from egress.yaml. DO NOT EDIT.

package cli

// egressDisclosure is the vendor-bound egress disclosure of invariant 6,
// rendered from egress.yaml. Exactly two categories; each names its switch,
// the vendor host it would reach and its retention. egressCategory is declared
// in privacy.go, which prints this disclosure.
var egressDisclosure = []egressCategory{
	{Name: "update-check", Switch: "TOKENHUSH_NO_UPDATE_CHECK", Host: "updates.tokenhush.com", Retention: "Vendor access logs and request records are retained for 30 days."},
	{Name: "rule-sync", Switch: "TOKENHUSH_NO_RULE_SYNC", Host: "updates.tokenhush.com", Retention: "Vendor access logs and request records are retained for 30 days."},
}
